### ISSUE TITLE
Training error with multiple GPUs

### ISSUE THREAD

**Issue by saikrishnadas** [WongKinYiu/ScaledYOLOv4#109]
Here is the screenshot to the issue ,
![Screenshot (141)](https://user-images.githubusercontent.com/30836867/103065594-fa561800-45dc-11eb-9bdc-944ccdcb2ed6.png)

@WongKinYiu

**Comment by WongKinYiu** [comment]
this error is about tensorboard.

**Comment by saikrishnadas** [comment]
What learning rate should i set if i train on a 8 gpu ?

**Comment by saikrishnadas** [comment]
Check this screenshot, I re-installed tensorboard. But now i get a cuda out of memory. 
![Screenshot (142)](https://user-images.githubusercontent.com/30836867/103080551-14ebb980-45fc-11eb-8c81-a478dbb21ae6.png)



@WongKinYiu

**Comment by WongKinYiu** [comment]
for 416 input resolution, better to use yolov4-csp.
and reduce batch size to fit your gpu vram.

**Comment by saikrishnadas** [comment]
My original image size is 1280 x 720 (width 1280 and height 720 pixels). Which input size is good to use if i need to train on a p7 model ?

**Comment by saikrishnadas** [comment]
@WongKinYiu

**Comment by WongKinYiu** [comment]
for p7, good to use 1536.

**Comment by saikrishnadas** [comment]
`python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 16 --img 1536 1536 --data '../data.yaml' --cfg ./models/yolov4-p7.yaml --weights '' --sync-bn --device 0,1,2,3 --name yolov4-p7`

I used this cmd to train the model. I use AWS ec2 instance with has 4 GPUs.
I killed all the running process(`nvidia-smi` and `kill id`), to make sure the gpus are free from processes.
and ran the cmd mentioned above with lower batch-size suggested by you if i run into memory issues.

I even tried this with a smaller model p5. 

but still i get this error,

```
RuntimeError: CUDA out of memory. Tried to allocate 180.00 MiB (GPU 0; 14.76 GiB total capacity; 13.33 GiB already allocated; 97.75 MiB free; 13.71 GiB reserved in total by PyTorch)
  0%|                                                  | 0/1000 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/bin/python', '-u', 'train.py', '--local_rank=3', '--batch-size', '16', '--img', '1536', '1536', '--data', '../data.yaml', '--cfg', './models/yolov4-p7.yaml', '--weights', '','--sync-bn', '--device', '0,1,2,3', '--name', 'yolov4-p7']' returned non-zero exit status 1.

```


@WongKinYiu

**Comment by JustinhoCHN** [comment]
> `python -m torch.distributed.launch --nproc_per_node 4 train.py --batch-size 16 --img 1536 1536 --data '../data.yaml' --cfg ./models/yolov4-p7.yaml --weights '' --sync-bn --device 0,1,2,3 --name yolov4-p7`
> 
> I used this cmd to train the model. I use AWS ec2 instance with has 4 GPUs.
> I killed all the running process(`nvidia-smi` and `kill id`), to make sure the gpus are free from processes.
> and ran the cmd mentioned above with lower batch-size suggested by you if i run into memory issues.
> 
> I even tried this with a smaller model p5.
> 
> but still i get this error,
> 
> ```
> RuntimeError: CUDA out of memory. Tried to allocate 180.00 MiB (GPU 0; 14.76 GiB total capacity; 13.33 GiB already allocated; 97.75 MiB free; 13.71 GiB reserved in total by PyTorch)
>   0%|                                                  | 0/1000 [00:03<?, ?it/s]
> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/ubuntu/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
>     main()
>   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
>     cmd=cmd)
> subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/bin/python', '-u', 'train.py', '--local_rank=3', '--batch-size', '16', '--img', '1536', '1536', '--data', '../data.yaml', '--cfg', './models/yolov4-p7.yaml', '--weights', '','--sync-bn', '--device', '0,1,2,3', '--name', 'yolov4-p7']' returned non-zero exit status 1.
> ```
> 
> @WongKinYiu

AWS p3.8xlarge using 16GB V100, which is insuffient for training p7, I tried that......

**Comment by sard0r** [comment]
@WongKinYiu  I am also having same problem I have 4 RTX 3090 GPUs (24gb) but while training only one is being uses others being idle. Is there any problem in the code?
