### ISSUE TITLE
KeyError: '/coco/images/val2017/000000000139.jpg'

### ISSUE THREAD

**Issue by LukeAI** [WongKinYiu/ScaledYOLOv4#124]
Hi, thanks for this repo! I can't get the test.py to work

I have a 2080Ti and up to date docker / nvidia-docker.

I do the following:

```
nvidia-docker run --name yolov4_csp -it -v /srv/datasets/coco/:/coco/ -v $(pwd)/:/yolo --shm-size=32g nvcr.io/nvidia/pytorch:20.06-py3
cd /
git clone https://github.com/JunnYu/mish-cuda
cd mish-cuda
python setup.py build install
cd /yolo
python test.py --img 640 --conf 0.001 --batch 8 --device 0 --data data/coco.yaml --cfg models/yolov4-csp.cfg --weights weights/yolov4-csp.weights
```

and get:
```
Namespace(augment=False, batch_size=8, cfg='models/yolov4-csp.cfg', conf_thres=0.001, data='data/coco.yaml', device='0', img_size=640, iou_thres=0.65, merge=False, names='data/coco.names', save_json=True, save_txt=False, single_cls=False, task='val', verbose=False, weights=['weights/yolov4-csp.weights'])
Using CUDA device0 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)

Model Summary: 342 layers, 5.29214e+07 parameters, 5.29214e+07 gradients
Traceback (most recent call last):
  File "test.py", line 297, in <module>
    opt.verbose)
  File "test.py", line 95, in test
    hyp=None, augment=False, cache=False, pad=0.5, rect=True)[0]
  File "/yolo/utils/datasets.py", line 60, in create_dataloader
    pad=pad)
  File "/yolo/utils/datasets.py", line 344, in __init__
    labels, shapes = zip(*[cache[x] for x in self.img_files])
  File "/yolo/utils/datasets.py", line 344, in <listcomp>
    labels, shapes = zip(*[cache[x] for x in self.img_files])
KeyError: '/coco/images/val2017/000000000139.jpg'
```

but `file /coco/images/val2017/000000000139.jpg` shows that the image is present.

I saw https://github.com/WongKinYiu/ScaledYOLOv4/issues/33 and tried deleting every .cache directory found by `find / -name ".cache"` and running again but it made no difference, please help!

**Comment by LukeAI** [comment]
ok worked this out. had to delete:

coco/labels/train2017.cache
coco/labels/val2017.cache

**Comment by KingfaLuis** [comment]
i do this : python train.py 
get the back
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    app.run(main)
  File "/home/yons/anaconda3/envs/smoke_test/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/yons/anaconda3/envs/smoke_test/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "train.py", line 152, in main
    for image_data, target in trainset:
  File "/home/sda8/lyf/yolov4/tensorflow-yolov4-tflite-master/core/dataset.py", line 147, in __next__
    image, bboxes = self.parse_annotation(annotation)
  File "/home/sda8/lyf/yolov4/tensorflow-yolov4-tflite-master/core/dataset.py", line 258, in parse_annotation
    raise KeyError("%s does not exist ... " % image_path)
KeyError: '/media/user/Source/Data/coco_dataset/coco/images/val2017/000000170595.jpg does not exist ... '
