### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 2. Got 36 and 35 (The offending index is 0)

### ISSUE THREAD

**Issue by cyrilzakka** [WongKinYiu/ScaledYOLOv4#138]
Hello,

Hope you're doing well! I was trying to extract the backbone of Yolov4-P5 to use for another project, and in the corresponding `yolov4-p5.yaml` I commented out https://github.com/WongKinYiu/ScaledYOLOv4/blob/0fc870c8bc3409405e65247d335f01dccea8dc1a/models/yolov4-p5.yaml#L52
so the network won't build it. Here is my final network: 
```
                from  n    params  module                                  arguments                     
  0                -1  1       928  models.common.Conv                      [3, 32, 3, 1]                 
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     19904  models.common.BottleneckCSP             [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  1   2614016  models.common.BottleneckCSP             [256, 256, 15]                
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1  10438144  models.common.BottleneckCSP             [512, 512, 15]                
  9                -1  1   4720640  models.common.Conv                      [512, 1024, 3, 2]             
 10                -1  1  20728832  models.common.BottleneckCSP             [1024, 1024, 7]               
 11                -1  1   7610368  models.common.SPPCSP                    [1024, 512, 1]                
 12                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 13                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 14                 8  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 15          [-1, -2]  1         0  models.common.Concat                    [1]                           
 16                -1  1   2298880  models.common.BottleneckCSP2            [512, 256, 3]                 
 17                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 18                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 19                 6  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 20          [-1, -2]  1         0  models.common.Concat                    [1]                           
 21                -1  1    576000  models.common.BottleneckCSP2            [256, 128, 3]                 
 22                -1  1    295424  models.common.Conv                      [128, 256, 3, 1]              
 23                -2  1    295424  models.common.Conv                      [128, 256, 3, 2]              
 24          [-1, 16]  1         0  models.common.Concat                    [1]                           
 25                -1  1   2298880  models.common.BottleneckCSP2            [512, 256, 3]                 
 26                -1  1   1180672  models.common.Conv                      [256, 512, 3, 1]              
 27                -2  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
 28          [-1, 11]  1         0  models.common.Concat                    [1]                           
 29                -1  1   9185280  models.common.BottleneckCSP2            [1024, 512, 3]                
 30                -1  1   4720640  models.common.Conv                      [512, 1024, 3, 1]             
Model Summary: 470 layers, 7.02237e+07 parameters, 7.02237e+07 gradients
```

After loading the weights into the created network like this:
```
ckpt = torch.load(path, map_location)
state_dict = ckpt['model'].float().state_dict()
state_dict = intersect_dicts(state_dict, self.state_dict(), exclude=[])
self.load_state_dict(state_dict, strict=False)
```
I tried training the network but I get the following error:
```
Traceback (most recent call last):
  File "train.py", line 746, in <module>
    train(0, args=args)
  File "train.py", line 455, in train
    net_outs = net(images,extras=extras)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/radar/yolact.py", line 1690, in forward
    outs = self.backbone(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/radar/backbone.py", line 660, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/content/radar/backbone.py", line 680, in forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/radar/models/common.py", line 168, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 36 and 35 (The offending index is 0)
```
I've been trying to debug it all day, but I can't seem to figure out why the size of the tensors differ by 1. Any insight?

**Comment by cyrilzakka** [comment]
Changing my `image_size` from 550 to 256 seems to have fixed the issue. I'm guessing it has to be a power of 2?

**Comment by LukeAI** [comment]
@cyrilzakka  it must be a multiple of 32

**Comment by clw5180** [comment]
> @cyrilzakka it must be a multiple of 32

Yes, are you doing some competition now?

**Comment by cyrilzakka** [comment]
@clw5180 not really, why?
