### ISSUE TITLE
模型加载问题

### ISSUE THREAD

**Issue by admin221** [WongKinYiu/ScaledYOLOv4#142]
import torch
weights = "runs/exp11_yolov4-p5/weights/best_yolov4-p5.pt"
model = torch.load(weights, map_location="cuda:0")
print(model)

在拉取的工程下执行这行代码可以正常打印模型结构，换到其他工程会打印下列错误，有遇到过的吗？

Traceback (most recent call last):
  File "/package/zz/project/zz-detect-scalev4/load.py", line 13, in <module>
    model = torch.load(weights, map_location="cuda:0")
  File "/home/hadoop/.local/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/hadoop/.local/lib/python3.7/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'

**Comment by WongKinYiu** [comment]
把models資料夾一起搬過去吧
