### ISSUE TITLE
May I run this repo without using nvidia-docker?

### ISSUE THREAD

**Issue by songyuc** [WongKinYiu/ScaledYOLOv4#144]
Hi, guys,
I want to know whether I can run this repo without using nvidia-docker, which is hard for me to run successfully on my PC.

Any answer or idea will appreciated!

**Comment by LukeAI** [comment]
I got it working in a virtualenv with python 3.6.9, CUDA 11.0

obviously got to make sure you get the right version of torch for your CUDA etc.

pip install -r requirements.txt

requirements.txt
```
pyyaml
torch
torchvision
tqdm
opencv-python
pillow-simd
matplotlib
scipy
pycocotools
tensorboard
```

**Comment by LukeAI** [comment]
although I have this problem https://github.com/WongKinYiu/ScaledYOLOv4/issues/139

no idea if that is actually a problem or related to my non-recommended setup

**Comment by songyuc** [comment]
HI, @LukeAI , but I failed on building mish-cuda, as
```bash
python setup.py build install
/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/extension.py:131: UserWarning: Unknown Extension options: 'headers'
  warnings.warn(msg)
running build
running build_py
running egg_info
writing src/mish_cuda.egg-info/PKG-INFO
writing dependency_links to src/mish_cuda.egg-info/dependency_links.txt
writing requirements to src/mish_cuda.egg-info/requires.txt
writing top-level names to src/mish_cuda.egg-info/top_level.txt
reading manifest file 'src/mish_cuda.egg-info/SOURCES.txt'
writing manifest file 'src/mish_cuda.egg-info/SOURCES.txt'
running build_ext
building 'mish_cuda._C' extension
Emitting ninja build file /home/eric/Research/Experiments/ScaledYOLOv4-csp/ScaledYOLOv4/test/mish-cuda/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] :/usr/local/cuda/bin/nvcc -I/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/include -I/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/include/TH -I/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/eric/anaconda3/envs/conda-general/include/python3.8 -c -c /home/eric/Research/Experiments/ScaledYOLOv4-csp/ScaledYOLOv4/test/mish-cuda/csrc/cuda/mish_kernel.cu -o /home/eric/Research/Experiments/ScaledYOLOv4-csp/ScaledYOLOv4/test/mish-cuda/build/temp.linux-x86_64-3.8/csrc/cuda/mish_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' --expt-extended-lambda -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/eric/Research/Experiments/ScaledYOLOv4-csp/ScaledYOLOv4/test/mish-cuda/build/temp.linux-x86_64-3.8/csrc/cuda/mish_kernel.o 
:/usr/local/cuda/bin/nvcc -I/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/include -I/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/include/TH -I/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/include/THC -I:/usr/local/cuda/include -I/home/eric/anaconda3/envs/conda-general/include/python3.8 -c -c /home/eric/Research/Experiments/ScaledYOLOv4-csp/ScaledYOLOv4/test/mish-cuda/csrc/cuda/mish_kernel.cu -o /home/eric/Research/Experiments/ScaledYOLOv4-csp/ScaledYOLOv4/test/mish-cuda/build/temp.linux-x86_64-3.8/csrc/cuda/mish_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' --expt-extended-lambda -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
/bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    setup(name='mish_cuda',
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/eric/anaconda3/envs/conda-general/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
Do you use built mish-cuda?

**Comment by LukeAI** [comment]
you haven't installed CUDA or it isn't in your path
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by LukeAI** [comment]
alternatively you could install with torch like:

`pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by songyuc** [comment]
@LukeAI , did you clone the mish-cuda in `cd /`?

**Comment by LukeAI** [comment]
no, just in some other directory, it doesn't matter where

**Comment by songyuc** [comment]
OK, that might be due to my PyTorch version.
Thanks sincerely for your information!
