### ISSUE TITLE
 can't install mish_cuda

### ISSUE THREAD

**Issue by yenai3726** [WongKinYiu/ScaledYOLOv4#162]
HI
i try to install mish-cuda by this instructions:

conda create -n scaled-yolov4 python=3.7 -y
conda install pytorch==1.7.0 torchvision==0.8.1 cudatoolkit=10.1 -c pytorch -y
git clone https://github.com/thomasbrandon/mish-cuda
cd mish-cuda
python setup.py build install

and i get message back:

`1 error detected in the compilation of "C:/Users/OwO/AppData/Local/Temp/tmpxft_0000079c_00000000-10_mish_kernel.cpp1.ii".
mish_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\anaconda\envs\pytor\lib\site-packages\torch\utils\cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "D:\anaconda\envs\pytor\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "D:\anaconda\envs\pytor\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\anaconda\envs\pytor\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\anaconda\envs\pytor\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "D:\anaconda\envs\pytor\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\anaconda\envs\pytor\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "D:\anaconda\envs\pytor\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda\envs\pytor\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\anaconda\envs\pytor\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\anaconda\envs\pytor\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "D:\anaconda\envs\pytor\lib\site-packages\torch\utils\cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "D:\anaconda\envs\pytor\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "D:\anaconda\envs\pytor\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\anaconda\envs\pytor\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\anaconda\envs\pytor\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "D:\anaconda\envs\pytor\lib\site-packages\torch\utils\cpp_extension.py", line 635, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "D:\anaconda\envs\pytor\lib\site-packages\torch\utils\cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "D:\anaconda\envs\pytor\lib\site-packages\torch\utils\cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for 

how can i fix this problem ?
thank you for your attention and answer!!

**Comment by WongKinYiu** [comment]
try `pip install git+https://github.com/JunnYu/mish-cuda.git`

**Comment by yenai3726** [comment]
thank for your note and  answer !!
I have tried to use this mish-cuda under pytorch=1.7   but it don't work 
and Readme.md in this archive
Explain to use Win10  / cuda10.1 / pytorch1.6 
 then i change my pytorch's version to 1.6  and he did work 
So I am sure the problem is only in the version mismatch
