### ISSUE TITLE
mish_cuda出错~

### ISSUE THREAD

**Issue by SpongeBab** [WongKinYiu/ScaledYOLOv4#197]
running build
running build_py
running egg_info
writing src/mish_cuda.egg-info/PKG-INFO
writing dependency_links to src/mish_cuda.egg-info/dependency_links.txt
writing requirements to src/mish_cuda.egg-info/requires.txt
writing top-level names to src/mish_cuda.egg-info/top_level.txt
reading manifest file 'src/mish_cuda.egg-info/SOURCES.txt'
writing manifest file 'src/mish_cuda.egg-info/SOURCES.txt'
running build_ext
building 'mish_cuda._C' extension
gcc -pthread -B /home/distribute-509/anaconda3/envs/Pytorch4TSN/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iexternal -I/home/distribute-509/anaconda3/envs/Pytorch4TSN/lib/python3.6/site-packages/torch/lib/include -I/home/distribute-509/anaconda3/envs/Pytorch4TSN/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/distribute-509/anaconda3/envs/Pytorch4TSN/lib/python3.6/site-packages/torch/lib/include/TH -I/home/distribute-509/anaconda3/envs/Pytorch4TSN/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/home/distribute-509/anaconda3/envs/Pytorch4TSN/include/python3.6m -c csrc/mish_cuda.cpp -o build/temp.linux-x86_64-3.6/csrc/mish_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
csrc/mish_cuda.cpp: In function ‘at::Tensor mish_forward(const at::Tensor&, c10::optional<at::Tensor>)’:
csrc/mish_cuda.cpp:13:27: error: ‘TensorArg’ is not a member of ‘torch’
   auto input_arg = torch::TensorArg(input, "input", 0);
                           ^~~~~~~~~
csrc/mish_cuda.cpp:13:27: note: suggested alternative: ‘tensor’
   auto input_arg = torch::TensorArg(input, "input", 0);
                           ^~~~~~~~~
                           tensor
csrc/mish_cuda.cpp:15:27: error: ‘TensorArg’ is not a member of ‘torch’
     auto out_arg = torch::TensorArg(*out, "out", 1);
                           ^~~~~~~~~
csrc/mish_cuda.cpp:15:27: note: suggested alternative: ‘tensor’
     auto out_arg = torch::TensorArg(*out, "out", 1);
                           ^~~~~~~~~
                           tensor
csrc/mish_cuda.cpp:16:12: error: ‘checkSameType’ is not a member of ‘torch’
     torch::checkSameType("mish_forward", input_arg, out_arg);
            ^~~~~~~~~~~~~
csrc/mish_cuda.cpp:17:12: error: ‘checkSameSize’ is not a member of ‘torch’
     torch::checkSameSize("mish_forward", input_arg, out_arg);
            ^~~~~~~~~~~~~
csrc/mish_cuda.cpp:28:7: error: ‘TORCH_CHECK’ was not declared in this scope
       TORCH_CHECK(false, "Unsupported device type, should be CPU or CUDA but got ", input.device().type());
       ^~~~~~~~~~~
csrc/mish_cuda.cpp:28:7: note: suggested alternative: ‘AT_CHECK’
       TORCH_CHECK(false, "Unsupported device type, should be CPU or CUDA but got ", input.device().type());
       ^~~~~~~~~~~
       AT_CHECK
csrc/mish_cuda.cpp: In function ‘at::Tensor mish_backward(const at::Tensor&, const at::Tensor&)’:
csrc/mish_cuda.cpp:35:27: error: ‘TensorArg’ is not a member of ‘torch’
   auto input_arg = torch::TensorArg(input, "input", 0);
                           ^~~~~~~~~
csrc/mish_cuda.cpp:35:27: note: suggested alternative: ‘tensor’
   auto input_arg = torch::TensorArg(input, "input", 0);
                           ^~~~~~~~~
                           tensor
csrc/mish_cuda.cpp:36:30: error: ‘TensorArg’ is not a member of ‘torch’
   auto grad_out_arg = torch::TensorArg(grad_out, "grad_out", 1);
                              ^~~~~~~~~
csrc/mish_cuda.cpp:36:30: note: suggested alternative: ‘tensor’
   auto grad_out_arg = torch::TensorArg(grad_out, "grad_out", 1);
                              ^~~~~~~~~
                              tensor
csrc/mish_cuda.cpp:37:10: error: ‘checkSameType’ is not a member of ‘torch’
   torch::checkSameType("mish_backward", input_arg, grad_out_arg);
          ^~~~~~~~~~~~~
csrc/mish_cuda.cpp:48:7: error: ‘TORCH_CHECK’ was not declared in this scope
       TORCH_CHECK(false, "Unsupported device type, should be CPU or CUDA but got ", input.device().type());
       ^~~~~~~~~~~
csrc/mish_cuda.cpp:48:7: note: suggested alternative: ‘AT_CHECK’
       TORCH_CHECK(false, "Unsupported device type, should be CPU or CUDA but got ", input.device().type());
       ^~~~~~~~~~~
       AT_CHECK
error: command 'gcc' failed with exit status 1

**Comment by WongKinYiu** [comment]
pytorch too new.
try pytorch <= 1.7.0, otherwise you have to modify the source code of mish_cuda.

**Comment by SpongeBab** [comment]
@WongKinYiu 
hi,my pytorch version is 1.0
but i successfully run it on pytorch 1.4.
maybe 1.0 is too old.
and i am in china ,you know i cannt download the weights from google.
can you give a other link。。。。。。
thanks very much

**Comment by WongKinYiu** [comment]
oh...too old.

maybe try to find someone upload them to baidu disk?

**Comment by SpongeBab** [comment]
@WongKinYiu 
hi,thanks for your so fast reply.
finally i run it successfully 。。。luckily
this is the output:
```
(GCN_pytorch) distribute-509@509:~/ScaledYOLOv4-yolov4-csp$ python test.py --img 640 --conf 0.001 --batch 8 --device 0 --data coco.yaml --cfg models/yolov4-csp.cfg --weights weights/yolov4-csp.weights
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-o0r864y2 because the default path (/home/distribute-509/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Namespace(augment=False, batch_size=8, cfg='models/yolov4-csp.cfg', conf_thres=0.001, data='./data/coco.yaml', device='0', img_size=640, iou_thres=0.65, merge=False, names='data/coco.names', save_json=True, save_txt=False, single_cls=False, task='val', verbose=False, weights=['weights/yolov4-csp.weights'])
Using CUDA device0 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=11019MB)

Model Summary: 342 layers, 5.29214e+07 parameters, 5.29214e+07 gradients
Traceback (most recent call last):
  File "/home/distribute-509/ScaledYOLOv4-yolov4-csp/utils/datasets.py", line 308, in __init__
    raise Exception('%s does not exist' % p)
Exception: ../coco/val2017.txt does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 284, in <module>
    opt.verbose)
  File "test.py", line 82, in test
    hyp=None, augment=False, cache=False, pad=0.5, rect=True)[0]
  File "/home/distribute-509/ScaledYOLOv4-yolov4-csp/utils/datasets.py", line 60, in create_dataloader
    pad=pad)
  File "/home/distribute-509/ScaledYOLOv4-yolov4-csp/utils/datasets.py", line 312, in __init__
    raise Exception('Error loading data from %s: %s\nSee %s' % (path, e, help_url))
Exception: Error loading data from ../coco/val2017.txt: ../coco/val2017.txt does not exist
```


Does it mean i must the whole cocodataset?then i can run test?

**Comment by DefTruth** [comment]
I have solved this error by new a script name "mish_cuda.py" in the root path of this project and put one line code into this script. After that i can convert .pt to .onnx and get correct output.   
* new a script name "mish_cuda.py" with one line code  
```python
from utils.activations import Mish as MishCuda
```  
Then the parser of torch.load will auto replace the "Mish" act module in pretrained model with this new one.   
my log:  
```shell
      (bn): BatchNorm2d(1024, eps=0.001, momentum=0.03, affine=True, track_running_stats=True)
      (act): Mish()
    )
    (42): Detect(
      (m): ModuleList(
        (0): Conv2d(256, 340, kernel_size=(1, 1), stride=(1, 1))
        (1): Conv2d(512, 340, kernel_size=(1, 1), stride=(1, 1))
        (2): Conv2d(1024, 340, kernel_size=(1, 1), stride=(1, 1))
        (3): Conv2d(1024, 340, kernel_size=(1, 1), stride=(1, 1))
      )
    )
  )
)
Detect self.training:  False 4
torch.Size([1, 34000, 85])

Starting ONNX export with onnx 1.8.0...
Detect self.training:  False 4

Checking 0/3...
Checking 1/3...
Checking 2/3...
input:  NodeArg(name='images', type='tensor(float)', shape=[1, 3, 640, 640])
output:  NodeArg(name='output', type='tensor(float)', shape=[1, 34000, 85])
output:  NodeArg(name='2273', type='tensor(float)', shape=[1, 4, 80, 80, 85])
output:  NodeArg(name='2371', type='tensor(float)', shape=[1, 4, 40, 40, 85])
output:  NodeArg(name='2469', type='tensor(float)', shape=[1, 4, 20, 20, 85])
output:  NodeArg(name='2567', type='tensor(float)', shape=[1, 4, 10, 10, 85])
ONNX export success, saved as ./weights/yolov4-p6-640-640.onnx

```

**Comment by sunlizhuang** [comment]
f**k mish_cuda

**Comment by sunlizhuang** [comment]
fuck mush_cuda
