### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by wuzuiyuzui** [WongKinYiu/ScaledYOLOv4#21]
Analyzing anchors... anchors/target = 7.18, Best Possible Recall (BPR) = 0.9972
Image sizes 640 train, 640 test
Using 4 dataloader workers
Starting training for 300 epochs...
  0%|          | 0/805 [00:00<?, ?it/s]
     Epoch   gpu_mem      GIoU       obj       cls     total   targets  img_size
  0%|          | 0/805 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/ljy/ScaledYOLOv4-yolov4-large/train.py", line 448, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/ljy/ScaledYOLOv4-yolov4-large/train.py", line 269, in train
    scaler.scale(loss).backward()
  File "/home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/autograd/__init__.py", line 125, in backward
    Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
Exception raised from findAlgorithms at /pytorch/aten/src/ATen/native/cudnn/Conv.cpp:550 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f2d0cd8d1e2 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xec42f7 (0x7f2d0e0ba2f7 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xebcf7e (0x7f2d0e0b2f7e in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xeb800e (0x7f2d0e0ae00e in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xeb9bfb (0x7f2d0e0afbfb in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #5: at::native::cudnn_convolution_backward_input(c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool) + 0xb2 (0x7f2d0e0b0152 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0xf1f35b (0x7f2d0e11535b in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xf4f178 (0x7f2d0e145178 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #8: at::cudnn_convolution_backward_input(c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool) + 0x1ad (0x7f2d48fed88d in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: at::native::cudnn_convolution_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x223 (0x7f2d0e0ae823 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #10: <unknown function> + 0xf1f445 (0x7f2d0e115445 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #11: <unknown function> + 0xf4f1d4 (0x7f2d0e1451d4 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #12: at::cudnn_convolution_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x1e2 (0x7f2d48ffc242 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x2ec9c62 (0x7f2d4acbfc62 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x2ede224 (0x7f2d4acd4224 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #15: at::cudnn_convolution_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x1e2 (0x7f2d48ffc242 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::generated::CudnnConvolutionBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x258 (0x7f2d4ab46c38 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x3375bb7 (0x7f2d4b16bbb7 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #18: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x1400 (0x7f2d4b167400 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #19: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x451 (0x7f2d4b167fa1 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #20: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x89 (0x7f2d4b160119 in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #21: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x4a (0x7f2d588fb86a in /home/ljy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #22: <unknown function> + 0xc9067 (0x7f2d5a25a067 in /home/ljy/anaconda3/envs/yolov5/bin/../lib/libstdc++.so.6)
frame #23: <unknown function> + 0x9609 (0x7f2d5e43a609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #24: clone + 0x43 (0x7f2d5e361293 in /lib/x86_64-linux-gnu/libc.so.6)

前面都是正常的，是我的环境有问题吗

**Comment by WongKinYiu** [comment]
Could you provide your training command?

By the way, I have not tested on python 3.8 and pytorch 1.7.

**Comment by wuzuiyuzui** [comment]
我的命令是  --batch-size 4 --cfg yolov4-p7.yaml --img 640 640 --data data/coco.yaml --weights 'yolov4-p7.pt' --sync-bn --device 0 --name yolov4-p7 --epochs 300                 Using CUDA device0 _CudaDeviceProperties(name='GeForce RTX 2080 Ti', total_memory=10997MB),我在试着换环境，您能提供以下您的运行环境吗，我这个环境跑那个U版的yolo3可以运行

**Comment by WongKinYiu** [comment]
batch先設1看看 p7有點大

**Comment by gulingfengze** [comment]
@WongKinYiu  你好， 可以提供一下训练测试环境吗？ 我这边测试pytorch1.6.0+cudatoolkit10.1 +cuda10.0(cuda10.1)+cudnn7.6.5 ，训练时报RuntimeError: CUDA error: invalid device function ，测试u版yolov5没问题。

**Comment by luyaozhi** [comment]
> @WongKinYiu 你好， 可以提供一下训练测试环境吗？ 我这边测试pytorch1.6.0+cudatoolkit10.1 +cuda10.0(cuda10.1)+cudnn7.6.5 ，训练时报RuntimeError: CUDA error: invalid device function ，测试u版yolov5没问题。

请问您修改成功了么，我的环境和你一样，也有同样的错误

**Comment by WongKinYiu** [comment]
[environment](https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-large#installation)

**Comment by gulingfengze** [comment]
@luyaozhi @WongKinYiu 暂时没解决。参考“Installation”成功安装了mc和mish cuda，但仍然会有上面的问题，所以很疑惑

**Comment by businiaoo** [comment]
> @luyaozhi @WongKinYiu 暂时没解决。参考“Installation”成功安装了mc和mish cuda，但仍然会有上面的问题，所以很疑惑

插个眼，同样的问题

**Comment by qutianzun** [comment]
我通过修改显存大小，就不再报这个错误

**Comment by qutianzun** [comment]
By modifying the size of the video memory, I no longer have this error

**Comment by qutianzun** [comment]
By modifying the size of the GPU memory, I no longer have this error

**Comment by 200987299** [comment]
> By modifying the size of the GPU memory, I no longer have this error

you mean change the batchsize, right?
