### ISSUE TITLE
YOLOv4-CSP: can't convert cuda:0 device type tensor to numpy

### ISSUE THREAD

**Issue by ghost** [WongKinYiu/ScaledYOLOv4#240]
I'm trying to train a custom dataset with YOLOv4-CSP. It always fails when calculating mAP etc. after training for an epoch, this is the error that is thrown:

```
Traceback (most recent call last):
  File "train.py", line 438, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 301, in train
    results, maps, times = test.test(opt.data,
  File "/root/ScaledYOLOv4-yolov4-csp/test.py", line 206, in test
    plot_images(img, output_to_target(output, width, height), paths, str(f), names)  # predictions
  File "/root/ScaledYOLOv4-yolov4-csp/utils/general.py", line 907, in output_to_target
    return np.array(targets)
  File "/usr/local/lib/python3.8/dist-packages/torch/tensor.py", line 621, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

What could be the problem?

**Comment by ghost** [comment]
I've tried the docker container as mentioned in the README and it works now. It seems to have been some sort of version mismatch, sorry for the troubles.
