### ISSUE TITLE
Error when running test.py

### ISSUE THREAD

**Issue by Edwardius** [WongKinYiu/ScaledYOLOv4#339]
Followed the steps given in READme.md. 

When testing, all three of the commands do not work, giving the following error message:

```
Namespace(augment=False, batch_size=8, conf_thres=0.001, data='./data/coco.yaml', device='0', img_size=1536, iou_thres=0.65, merge=False, save_json=True, save_txt=False, single_cls=False, task='val', verbose=False, weights=['weights/yolov4-p7.pt'])
Using CUDA device0 _CudaDeviceProperties(name='NVIDIA GeForce RTX 3080', total_memory=10010MB)

Fusing layers... Traceback (most recent call last):
  File "test.py", line 278, in <module>
    opt.verbose)
  File "test.py", line 55, in test
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/yolo/models/experimental.py", line 137, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/yolo/models/yolo.py", line 161, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "/yolo/utils/torch_utils.py", line 117, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.size()))
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

Is there something wrong with the CUDA version?

Machine Specs:
RTX 3080
AMD Ryzen 5800x
Ubuntu 20.04.3 LTS 64-bit

If this is a simple issue, sorry.
If not, thanks for the help!

**Comment by WongKinYiu** [comment]
yes, you could try nvcr.io/nvidia/pytorch:20.11-py3
