### ISSUE TITLE
Train.py runtime error, Float can't be cast to the desired output type long int

### ISSUE THREAD

**Issue by mimslim** [WongKinYiu/ScaledYOLOv4#406]
Hi.   I have had success in the past with this ScaledYOLOv4 code, but am now getting the failure mentioned.   I have seen this same error mentioned on a YOLOV5 github issue list:  https://github.com/ultralytics/yolov5/issues/8405
That one was related, I believe, to incompatibility of the code with Torch 1.12.   Maybe an earlier version of Torch is required?  I am using:  torch 1.12.1+cu113 

error message:
Traceback (most recent call last):
  File "train.py", line 443, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 260, in train
    loss, loss_items = compute_loss(pred, targets.to(device), model)  # scaled by batch_size
  File "/content/ScaledYOLOv4/utils/general.py", line 446, in compute_loss
    tcls, tbox, indices, anchors = build_targets(p, targets, model)  # targets
  File "/content/ScaledYOLOv4/utils/general.py", line 556, in build_targets
    indices.append((b, a, gj.clamp_(0, gain[3]), gi.clamp_(0, gain[2])))  # image, anchor, grid indices
RuntimeError: result type Float can't be cast to the desired output type long int
CPU times: user 415 ms, sys: 83.6 ms, total: 499 ms

**Comment by mimslim** [comment]
Fixed this by reverting to torch 1.8, like this:
!pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html
