### ISSUE TITLE
Error while training the yolov7 model _pickle.UnpicklingError: STACK_GLOBAL requires str

### ISSUE THREAD

**Issue by Hetsoni2002** [WongKinYiu/ScaledYOLOv4#416]
Transferred 169/644 items from yolov7.pt
Scaled weight_decay = 0.0005
Optimizer groups: 108 .bias, 108 conv.weight, 111 other
Traceback (most recent call last):
  File "/home/hetsoni/work/crack_detection/yolov7/yolov7/train.py", line 613, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/hetsoni/work/crack_detection/yolov7/yolov7/train.py", line 245, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "/home/hetsoni/work/crack_detection/yolov7/yolov7/utils/datasets.py", line 69, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/home/hetsoni/work/crack_detection/yolov7/yolov7/utils/datasets.py", line 392, in __init__
    cache, exists = torch.load(cache_path), True  # load
  File "/home/hetsoni/.local/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/hetsoni/.local/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: STACK_GLOBAL requires str
Traceback (most recent call last):
  File "/home/hetsoni/work/crack_detection/yolov7/yolov7/train.py", line 613, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/hetsoni/work/crack_detection/yolov7/yolov7/train.py", line 245, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "/home/hetsoni/work/crack_detection/yolov7/yolov7/utils/datasets.py", line 69, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/home/hetsoni/work/crack_detection/yolov7/yolov7/utils/datasets.py", line 392, in __init__
    cache, exists = torch.load(cache_path), True  # load
  File "/home/hetsoni/.local/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/hetsoni/.local/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: STACK_GLOBAL requires str

**Comment by Hetsoni2002** [comment]
I don't know what to do here please help and also it is showing that the urllib and chardet are not of supported type how can i resolve that

(yolov7) hetsoni@Legion:~/work/crack_detection/yolov7/yolov7$ python3 train.py --workers 1 --batch-size 8 --epoch 100 --img 640 640 --device 0 --data train_data/data.yaml --weights yolov7.pt --cfg cfg/training/custom.yaml --name yolov7-custom
/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.0.3) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

**Comment by Hetsoni2002** [comment]
so far i have tried to clear the cache files and changing the urllib version but it did not work
