### ISSUE TITLE
inference yolov4-p5 error

### ISSUE THREAD

**Issue by xuanzhangyang** [WongKinYiu/ScaledYOLOv4#61]
at branch yolov4-large:
python detect.py --device 6 --weight weights/yolov4-p5.pt --cfg models/yolov4.cfg 

error:
Traceback (most recent call last):
  File "detect.py", line 190, in <module>
    detect()
  File "detect.py", line 48, in detect
    load_darknet_weights(model, weights[0])
  File "/home/xuan/code/pytorch/ScaledYOLOv4/models/models.py", line 441, in load_darknet_weights
    conv.weight.data.copy_(torch.from_numpy(weights[ptr:ptr + nw]).view_as(conv.weight))
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 2071138

So what is the model input size ?

**Comment by WongKinYiu** [comment]
it due to you use model of yolov4-csp branch to inference weights of yolov4-large branch.
the size is not the problem.
